# Site Settings
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Napal Roy
tagline: Graphic Designer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'To provide myself in a prospective position in a well-reputed organization and earnings in a perfect corporate culture by virtue of professional efficiency and effectivenes.
You can <a href="#" target="_blank">download this free resume/CV template here</a>.

#sidebar links
email: napalroy045@gmail.com
phone: 01830649501
website: blog.webjeda.com #do not add http://
linkedin: alandoe
github: sharu725
twitter: 
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

theme: jekyll-theme-cayman
